// vamos criar um loop com var
for(var i =0; i < 10; i++){
    console.log(i);
};
// o laço for é um laço de repetição 
// o for tem 3 parte , a primeira parte é a declaração de uma variavel:var i =0; a segunda parte é a condição que ele vai ser usando para ser repentino: i < 10; é a treceiro o incremento: i++

// vimos que quando executamos um valor ele vai ser repetir ate o valor for menor ou igual a 10
console.log('i=',i);
// vimos que quando executamos o valor de i fora do bloco vai mostra o valor que ele recebeu que foi 10
